"""Generate fleet/protocol.py from protocol/schemas + protocol/catalog.json.

    python scripts/gen.py           rewrite fleet/protocol.py
    python scripts/gen.py --check   exit 1 if fleet/protocol.py differs from what gen would write

The wire format is plain JSON, and the SDK hands messages around as the dicts
json.loads returns, so every object schema becomes a TypedDict: static types for
editors and type checkers, zero runtime cost, no conversion layer.

The protocol uses a small, known subset of JSON Schema. This generator handles
exactly that subset and raises on any keyword it does not understand, so a schema
change that needs new handling fails loudly here instead of producing a wrong type.
It mirrors sdk/typescript/scripts/gen.ts; naming matches it (message payloads are
`<PascalType>Payload`, other definitions PascalCase of their $defs key).

Standard library only, so it runs before the package's dependencies are installed.
"""

from __future__ import annotations

import json
import keyword
import re
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
PROTOCOL = HERE.parent.parent.parent / "protocol"
SCHEMAS = PROTOCOL / "schemas"
OUT = HERE.parent / "fleet" / "protocol.py"

HEADER = (
    "# Code generated by sdk/python/scripts/gen.py from protocol/. DO NOT EDIT.\n"
    "# Regenerate with `python scripts/gen.py` (in sdk/python).\n"
)

# Keywords that constrain values but do not change the Python type.
VALIDATION_ONLY = {
    "minLength", "maxLength", "pattern", "format",
    "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf",
    "minItems", "maxItems", "uniqueItems",
}
ANNOTATIONS = {"$schema", "$id", "title", "description", "$comment", "examples", "default"}
HANDLED = {
    "type", "properties", "required", "additionalProperties", "items",
    "enum", "const", "$ref", "oneOf", "anyOf", "$defs",
}

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class GenError(Exception):
    pass


def fail(where: str, msg: str) -> None:
    raise GenError(f"gen: {where}: {msg}")


def pascal(name: str) -> str:
    return "".join(p[0].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]+", name) if p)


def py_literal(v: Any, where: str) -> str:
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if v is None:
        return "None"
    fail(where, f"unsupported literal {v!r}")
    raise AssertionError  # unreachable


def union(parts: list[str]) -> str:
    uniq = list(dict.fromkeys(parts))
    return uniq[0] if len(uniq) == 1 else f"Union[{', '.join(uniq)}]"


class Generator:
    def __init__(self) -> None:
        self.catalog = json.loads((PROTOCOL / "catalog.json").read_text(encoding="utf-8"))
        self.schemas: dict[str, dict[str, Any]] = {
            p.name: json.loads(p.read_text(encoding="utf-8"))
            for p in sorted(SCHEMAS.glob("*.schema.json"))
        }
        if not self.schemas:
            fail(str(SCHEMAS), "no schemas found")

        self.names: dict[tuple[str, str], str] = {}  # (file, def) -> Python name; def "" = root
        env_file, env_def = self.split_pointer(self.catalog["envelope"], "")
        if env_def != "":
            fail("catalog.envelope", "must point at a schema root")
        self.names[(env_file, "")] = "RawEnvelope"
        for typ, pointer in self.catalog["messages"].items():
            file, d = self.split_pointer(pointer, "")
            if not d or d not in self.schemas[file].get("$defs", {}):
                fail(f"catalog {typ}", f"{pointer} does not resolve")
            self.names[(file, d)] = f"{pascal(typ)}Payload"
        for file, schema in self.schemas.items():
            for d in schema.get("$defs", {}):
                self.names.setdefault((file, d), pascal(d))

        self.decls: list[str] = []
        self.done: set[tuple[str, str]] = set()
        self.in_progress: set[tuple[str, str]] = set()
        self.taken: dict[str, str] = {}  # Python name -> where it came from

    # ---- refs ----------------------------------------------------------------

    def split_pointer(self, pointer: str, from_file: str) -> tuple[str, str]:
        path, _, frag = pointer.partition("#")
        file = re.sub(r"^schemas/", "", path) if path else from_file
        if file not in self.schemas:
            fail(pointer, f"unknown schema file {file}")
        if frag in ("", "/"):
            return file, ""
        m = re.fullmatch(r"/\$defs/([^/]+)", frag)
        if not m:
            fail(pointer, "only #/$defs/<name> refs are supported")
        return file, m.group(1)

    def claim_name(self, name: str, where: str) -> None:
        if name in self.taken:
            fail(where, f"type name {name} collides with {self.taken[name]}")
        self.taken[name] = where

    def ensure(self, key: tuple[str, str]) -> str:
        """Declare the definition behind `key` (dependencies first); return its name."""
        name = self.names.get(key)
        if name is None:
            fail(f"{key[0]}#{key[1]}", "unresolved $ref")
        if key in self.done:
            return name
        if key in self.in_progress:
            fail(f"{key[0]}#{key[1]}", "recursive $ref is not supported")
        self.in_progress.add(key)
        file, d = key
        schema = self.schemas[file]
        if d == "":
            body = {k: v for k, v in schema.items() if k != "$defs"}
            where = file
        else:
            body = schema["$defs"][d]
            where = f"{file}#/$defs/{d}"
        self.declare(name, body, file, where)
        self.in_progress.discard(key)
        self.done.add(key)
        return name

    # ---- rendering -----------------------------------------------------------

    def check_keywords(self, schema: dict[str, Any], where: str) -> None:
        for k in schema:
            if k not in HANDLED and k not in VALIDATION_ONLY and k not in ANNOTATIONS:
                fail(where, f'unsupported JSON Schema keyword "{k}" (teach scripts/gen.py about it)')

    @staticmethod
    def is_record(schema: Any) -> bool:
        """An object schema that becomes a TypedDict (it names its keys, or allows none)."""
        return (
            isinstance(schema, dict)
            and schema.get("type") == "object"
            and "oneOf" not in schema
            and "anyOf" not in schema
            and (bool(schema.get("properties")) or schema.get("additionalProperties") is False)
        )

    def render(self, schema: Any, file: str, where: str, hint: str) -> str:
        """Return a type expression; `hint` names any nested TypedDict this needs."""
        if schema is True:
            return "Any"
        if schema is False:
            fail(where, "false schema is not supported")
        if not isinstance(schema, dict):
            fail(where, f"schema must be an object or boolean, got {schema!r}")
        self.check_keywords(schema, where)

        if "$ref" in schema:
            extra = [k for k in schema if k != "$ref" and k not in ANNOTATIONS]
            if extra:
                fail(where, f"$ref with sibling keywords ({', '.join(extra)}) is not supported")
            return self.ensure(self.split_pointer(schema["$ref"], file))
        if "const" in schema:
            return f"Literal[{py_literal(schema['const'], where)}]"
        if "enum" in schema:
            return f"Literal[{', '.join(py_literal(v, where) for v in schema['enum'])}]"

        variants = schema.get("oneOf", schema.get("anyOf"))
        if variants is not None:
            if "oneOf" in schema and "anyOf" in schema:
                fail(where, "oneOf together with anyOf is not supported")
            if self.required_only(variants):
                # Needs its own name for the per-branch TypedDicts.
                self.declare(hint, schema, file, where)
                return hint
            rest = [k for k in schema if k not in ("oneOf", "anyOf") and k in HANDLED]
            if rest:
                fail(where, f"oneOf/anyOf alongside {', '.join(rest)} is not supported")
            return union([
                self.render(b, file, f"{where}/oneOf/{i}", f"{hint}{i}")
                for i, b in enumerate(variants)
            ])

        typ = schema.get("type")
        if isinstance(typ, list):
            return union([self.render({"type": t}, file, where, hint) for t in typ])
        if typ == "string":
            return "str"
        if typ in ("number",):
            return "float"
        if typ == "integer":
            return "int"
        if typ == "boolean":
            return "bool"
        if typ == "null":
            return "None"
        if typ == "array":
            if "items" not in schema:
                return "list[Any]"
            return f"list[{self.render(schema['items'], file, f'{where}/items', f'{hint}Item')}]"
        if typ == "object":
            if self.is_record(schema):
                self.declare(hint, schema, file, where)
                return hint
            extra = schema.get("additionalProperties")
            if extra is None or extra is True:
                return "dict[str, Any]"
            value = self.render(extra, file, f"{where}/additionalProperties", f"{hint}Value")
            return f"dict[str, {value}]"
        if typ is None:
            if all(k in ANNOTATIONS for k in schema):
                return "Any"
            fail(where, "schema without type, $ref, const, enum or oneOf")
        fail(where, f"unsupported type {typ!r}")
        raise AssertionError  # unreachable

    @staticmethod
    def required_only(variants: list[Any]) -> bool:
        return all(isinstance(b, dict) and set(b) == {"required"} for b in variants)

    # ---- declarations --------------------------------------------------------

    def declare(self, name: str, schema: Any, file: str, where: str) -> None:
        self.claim_name(name, where)
        desc = schema.get("description") if isinstance(schema, dict) else None
        src = f"Source: `protocol/schemas/{where}`"
        doc = f"{desc}\n\n{src}" if desc else src
        nested = re.sub(r"Payload$", "", name)

        if isinstance(schema, dict) and schema.get("type") == "object":
            variants = schema.get("oneOf", schema.get("anyOf"))
            if variants is not None and self.required_only(variants):
                self.declare_required_only(name, schema, variants, file, where, doc, nested)
                return
            if self.is_record(schema):
                self.check_keywords(schema, where)
                self.emit_typeddict(name, schema, schema.get("required", []), file, where, doc, nested)
                return

        expr = self.render(schema, file, where, nested)
        self.decls.append(f"{comment(doc)}{name} = {expr}\n")

    def declare_required_only(
        self, name: str, schema: dict[str, Any], variants: list[dict[str, Any]],
        file: str, where: str, doc: str, nested: str,
    ) -> None:
        """{a?, b?} + oneOf[{required:[a]}, {required:[b]}] -> one TypedDict per branch."""
        self.check_keywords(schema, where)
        props = schema.get("properties") or fail(where, "required-only branches need object properties")
        if schema.get("additionalProperties") is not False:
            fail(where, "required-only branches need additionalProperties: false")
        # Keys that only appear in *other* branches' `required` are excluded from each branch.
        branch_keys = {k for b in variants for k in b["required"]}
        branch_names = []
        for i, b in enumerate(variants):
            for k in b["required"]:
                if k not in props:
                    fail(f"{where}/oneOf/{i}", f'required "{k}" is not a declared property')
            bname = f"{nested}{''.join(pascal(k) for k in b['required'])}"
            sub = dict(schema)
            del sub["oneOf" if "oneOf" in schema else "anyOf"]
            sub["properties"] = {
                k: v for k, v in props.items() if k not in branch_keys or k in b["required"]
            }
            required = list(dict.fromkeys([*schema.get("required", []), *b["required"]]))
            bdoc = f"Branch of {name}: sets {', '.join(f'`{k}`' for k in b['required'])}.\n\n" \
                   f"Source: `protocol/schemas/{where}/oneOf/{i}`"
            self.claim_name(bname, f"{where}/oneOf/{i}")
            self.emit_typeddict(bname, sub, required, file, f"{where}/oneOf/{i}", bdoc, bname)
            branch_names.append(bname)
        self.decls.append(f"{comment(doc)}{name} = {union(branch_names)}\n")

    def emit_typeddict(
        self, name: str, schema: dict[str, Any], required: list[str],
        file: str, where: str, doc: str, nested: str,
    ) -> None:
        props: dict[str, Any] = schema.get("properties", {})
        extra = schema.get("additionalProperties")
        if extra is not False:
            fail(where, "an object with declared properties must set additionalProperties: false")
        for k in required:
            if k not in props:
                fail(where, f'required "{k}" is not a declared property')
        fields: list[tuple[str, str, str | None]] = []
        for k, p in props.items():
            t = self.render(p, file, f"{where}/properties/{k}", f"{nested}{pascal(k)}")
            if k not in required:
                t = f"NotRequired[{t}]"
            pdesc = p.get("description") if isinstance(p, dict) else None
            fields.append((k, t, pdesc))

        if all(IDENT.match(k) and not keyword.iskeyword(k) for k, _, _ in fields):
            lines = [f"class {name}(TypedDict):", docstring(doc)]
            if fields:
                lines.append("")
            for k, t, pdesc in fields:
                if pdesc:
                    lines.extend(f"    #: {ln}".rstrip() for ln in pdesc.split("\n"))
                lines.append(f"    {k}: {t}")
            self.decls.append("\n".join(lines) + "\n")
        else:
            # A key that is not a Python identifier (e.g. `from`) needs the functional form.
            lines = [f"{comment(doc)}{name} = TypedDict(", f"    {json.dumps(name)},", "    {"]
            for k, t, pdesc in fields:
                if pdesc:
                    lines.extend(f"        # {ln}".rstrip() for ln in pdesc.split("\n"))
                lines.append(f"        {json.dumps(k)}: {t},")
            lines += ["    },", ")"]
            self.decls.append("\n".join(lines) + "\n")

    # ---- output --------------------------------------------------------------

    def module(self) -> str:
        for file, schema in self.schemas.items():
            if (file, "") in self.names:
                self.ensure((file, ""))
            elif "type" in schema or "properties" in schema:
                fail(file, "schema root has a type but is not referenced by the catalog")
            for d in schema.get("$defs", {}):
                self.ensure((file, d))

        types = list(self.catalog["messages"])
        type_lits = ",\n".join(f"    {json.dumps(t)}" for t in types)
        type_tuple = "\n".join(f"    {json.dumps(t)}," for t in types)
        payloads = "\n".join(f"    {json.dumps(t)}: {pascal(t)}Payload," for t in types)
        return f'''{HEADER}"""Protocol types for fleet-server, generated from protocol/schemas.

Every message is plain JSON; these TypedDicts describe the dicts `json.loads`
returns and `json.dumps` accepts. They cost nothing at runtime.
"""

import sys
from typing import Any, Final, Literal, Union

if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict
else:  # NotRequired arrived in 3.11; typing_extensions backports it with a TypedDict that honours it.
    from typing_extensions import NotRequired, TypedDict


{(chr(10) * 2).join(self.decls)}

#: Envelope `v` this SDK speaks (protocol/catalog.json).
PROTOCOL_VERSION: Final = {py_literal(self.catalog["v"], "catalog.v")}

MessageType = Literal[
{type_lits},
]

#: Every message type in protocol/catalog.json, in catalog order.
MESSAGE_TYPES: Final[tuple[MessageType, ...]] = (
{type_tuple}
)

#: Payload TypedDict for each envelope `type` in protocol/catalog.json.
PAYLOAD_TYPES: Final[dict[str, Any]] = {{
{payloads}
}}
'''


def comment(doc: str) -> str:
    return "".join(f"# {ln}".rstrip() + "\n" for ln in doc.split("\n"))


def docstring(doc: str) -> str:
    if '"""' in doc or "\\" in doc:
        fail("description", 'descriptions may not contain """ or backslashes')
    lines = doc.split("\n")
    if len(lines) == 1:
        return f'    """{lines[0]}"""'
    body = "\n".join(f"    {ln}".rstrip() for ln in lines)
    return f'    """{body.lstrip()}\n    """'


def main(argv: list[str]) -> int:
    try:
        content = Generator().module()
    except GenError as e:
        print(e, file=sys.stderr)
        return 1
    rel = OUT.relative_to(HERE.parent)
    if "--check" in argv:
        if not OUT.exists():
            problem = "missing"
        elif OUT.read_text(encoding="utf-8") != content:
            problem = "out of date"
        else:
            print(f"{rel} is up to date.")
            return 0
        print(
            f"{rel} is {problem} relative to protocol/.\n"
            "Run `python scripts/gen.py` in sdk/python and commit the result.",
            file=sys.stderr,
        )
        return 1
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
