// Generates src/generated/ from protocol/schemas + protocol/catalog.json.
//
//   npm run gen          rewrite src/generated/
//   npm run gen:check    exit 1 if src/generated/ differs from what gen would write
//
// The protocol uses a small, known subset of JSON Schema. This generator handles
// exactly that subset and throws on any keyword it does not understand, so a schema
// change that needs new handling fails loudly here instead of producing a wrong type.

import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const PROTOCOL = resolve(HERE, "../../../protocol");
const SCHEMAS = join(PROTOCOL, "schemas");
const OUT = resolve(HERE, "../src/generated");

const HEADER =
  "// Code generated by sdk/typescript/scripts/gen.ts from protocol/. DO NOT EDIT.\n" +
  "// Regenerate with `npm run gen` (in sdk/typescript).\n";

type Schema = boolean | { [k: string]: any };

interface Catalog {
  v: number;
  envelope: string;
  messages: Record<string, string>;
}

// Keywords that constrain values but do not change the TypeScript type.
const VALIDATION_ONLY = new Set([
  "minLength", "maxLength", "pattern", "format",
  "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf",
  "minItems", "maxItems", "uniqueItems",
]);
const ANNOTATIONS = new Set(["$schema", "$id", "title", "description", "$comment", "examples", "default"]);
const HANDLED = new Set([
  "type", "properties", "required", "additionalProperties", "items",
  "enum", "const", "$ref", "oneOf", "anyOf", "$defs",
]);

function pascal(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join("");
}

function fail(where: string, msg: string): never {
  throw new Error(`gen: ${where}: ${msg}`);
}

// ---- load ------------------------------------------------------------------

const catalog: Catalog = JSON.parse(readFileSync(join(PROTOCOL, "catalog.json"), "utf8"));
const files = readdirSync(SCHEMAS).filter((f) => f.endsWith(".schema.json")).sort();
const schemas = new Map<string, Record<string, any>>(
  files.map((f) => [f, JSON.parse(readFileSync(join(SCHEMAS, f), "utf8"))]),
);

// "schemas/auth.schema.json#/$defs/hello" -> ["auth.schema.json", "hello"]; root -> [file, ""]
function splitPointer(pointer: string, fromFile: string): [string, string] {
  const [path, frag = ""] = pointer.split("#");
  const file = path ? path.replace(/^schemas\//, "") : fromFile;
  if (!schemas.has(file)) fail(pointer, `unknown schema file ${file}`);
  if (frag === "" || frag === "/") return [file, ""];
  const m = /^\/\$defs\/([^/]+)$/.exec(frag);
  if (!m) fail(pointer, "only #/$defs/<name> refs are supported");
  return [file, m[1]!];
}

// ---- naming ----------------------------------------------------------------
// Message payloads are named after their catalog type + "Payload" (hello ->
// HelloPayload); every other definition is PascalCase of its $defs key.

const names = new Map<string, string>(); // "file#def" -> TS name
const messageByKey = new Map<string, string>(); // "file#def" -> message type

const [envFile, envDef] = splitPointer(catalog.envelope, "");
if (envDef !== "") fail("catalog.envelope", "must point at a schema root");
names.set(`${envFile}#`, "RawEnvelope");

for (const [type, pointer] of Object.entries(catalog.messages)) {
  const [file, def] = splitPointer(pointer, "");
  if (!def || !schemas.get(file)!.$defs?.[def]) fail(`catalog ${type}`, `${pointer} does not resolve`);
  messageByKey.set(`${file}#${def}`, type);
  names.set(`${file}#${def}`, `${pascal(type)}Payload`);
}
for (const [file, schema] of schemas) {
  for (const def of Object.keys(schema.$defs ?? {})) {
    const key = `${file}#${def}`;
    if (!names.has(key)) names.set(key, pascal(def));
  }
}
{
  const seen = new Map<string, string>();
  for (const [key, name] of names) {
    if (seen.has(name)) fail(key, `type name ${name} collides with ${seen.get(name)}`);
    seen.set(name, key);
  }
}

// ---- rendering -------------------------------------------------------------

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const pad = (n: number) => "  ".repeat(n);
const propKey = (k: string) => (IDENT.test(k) ? k : JSON.stringify(k));
const paren = (t: string) => (/[|&]/.test(t) ? `(${t})` : t);

function doc(schema: Schema, indent: number): string {
  if (typeof schema !== "object" || typeof schema.description !== "string") return "";
  const lines = schema.description.split("\n");
  return lines.length === 1
    ? `${pad(indent)}/** ${lines[0]} */\n`
    : `${pad(indent)}/**\n${lines.map((l: string) => `${pad(indent)} * ${l}`.trimEnd()).join("\n")}\n${pad(indent)} */\n`;
}

function checkKeywords(schema: Record<string, any>, where: string) {
  for (const k of Object.keys(schema)) {
    if (!HANDLED.has(k) && !VALIDATION_ONLY.has(k) && !ANNOTATIONS.has(k)) {
      fail(where, `unsupported JSON Schema keyword "${k}" (teach scripts/gen.ts about it)`);
    }
  }
}

function render(schema: Schema, file: string, where: string, indent: number): string {
  if (schema === true) return "unknown";
  if (schema === false) return "never";
  checkKeywords(schema, where);

  if (schema.$ref !== undefined) {
    const extra = Object.keys(schema).filter((k) => k !== "$ref" && !ANNOTATIONS.has(k));
    if (extra.length) fail(where, `$ref with sibling keywords (${extra.join(", ")}) is not supported`);
    const [f, d] = splitPointer(schema.$ref, file);
    const name = names.get(`${f}#${d}`);
    if (!name) fail(where, `unresolved $ref ${schema.$ref}`);
    return name;
  }
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum !== undefined) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");

  const variants = schema.oneOf ?? schema.anyOf;
  if (variants !== undefined) {
    if (schema.oneOf && schema.anyOf) fail(where, "oneOf together with anyOf is not supported");
    // Branches that only add `required` narrow the parent object: {a?, b?} & ({a} | {b}).
    const requiredOnly = variants.every(
      (b: Schema) => typeof b === "object" && Object.keys(b).every((k) => k === "required"),
    );
    if (requiredOnly) {
      if (schema.type !== "object" || !schema.properties) fail(where, "required-only branches need object properties");
      const base = renderObject(schema, file, where, indent);
      const branches = variants.map((b: Record<string, any>, i: number) => {
        const fields = b.required.map((k: string) => {
          const p = schema.properties[k];
          if (p === undefined) fail(`${where}/oneOf/${i}`, `required "${k}" is not a declared property`);
          return `${propKey(k)}: ${render(p, file, `${where}/properties/${k}`, indent + 1)}`;
        });
        return `{ ${fields.join("; ")} }`;
      });
      return `${base} & (${branches.join(" | ")})`;
    }
    const union = variants
      .map((b: Schema, i: number) => paren(render(b, file, `${where}/oneOf/${i}`, indent)))
      .join(" | ");
    const rest = Object.keys(schema).filter((k) => k !== "oneOf" && k !== "anyOf" && HANDLED.has(k));
    if (rest.length) fail(where, `oneOf/anyOf alongside ${rest.join(", ")} is not supported`);
    return union;
  }

  const type = schema.type;
  if (Array.isArray(type)) {
    return type.map((t: string) => render({ type: t }, file, where, indent)).join(" | ");
  }
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return schema.items === undefined
        ? "unknown[]"
        : `${paren(render(schema.items, file, `${where}/items`, indent))}[]`;
    case "object":
      return renderObject(schema, file, where, indent);
    case undefined:
      if (Object.keys(schema).every((k) => ANNOTATIONS.has(k))) return "unknown";
      fail(where, "schema without type, $ref, const, enum or oneOf");
    default:
      fail(where, `unsupported type ${JSON.stringify(type)}`);
  }
}

function renderObject(schema: Record<string, any>, file: string, where: string, indent: number): string {
  const props: Record<string, Schema> = schema.properties ?? {};
  const required = new Set<string>(schema.required ?? []);
  const extra: Schema | undefined = schema.additionalProperties;
  const lines: string[] = [];
  for (const [k, p] of Object.entries(props)) {
    const t = render(p, file, `${where}/properties/${k}`, indent + 1);
    lines.push(`${doc(p, indent + 1)}${pad(indent + 1)}${propKey(k)}${required.has(k) ? "" : "?"}: ${t};`);
  }
  if (extra === false) {
    if (lines.length === 0) return "Record<string, never>";
  } else {
    if (lines.length > 0 && extra !== undefined && extra !== true) {
      fail(where, "typed additionalProperties next to declared properties is not supported");
    }
    const t = extra === undefined ? "unknown" : render(extra, file, `${where}/additionalProperties`, indent + 1);
    lines.push(`${pad(indent + 1)}[k: string]: ${t};`);
  }
  return `{\n${lines.join("\n")}\n${pad(indent)}}`;
}

function declare(name: string, schema: Schema, file: string, where: string): string {
  const body = render(schema, file, where, 0);
  const src = `Source: \`protocol/schemas/${where}\``;
  const desc = typeof schema === "object" && typeof schema.description === "string" ? schema.description : "";
  const d = doc({ description: desc ? `${desc}\n\n${src}` : src }, 0);
  const isPlainObject = body.startsWith("{\n") && body.endsWith("}");
  return isPlainObject ? `${d}export interface ${name} ${body}\n` : `${d}export type ${name} = ${body};\n`;
}

// ---- outputs ---------------------------------------------------------------

function protocolTs(): string {
  const decls: string[] = [];
  for (const [file, schema] of schemas) {
    const rootName = names.get(`${file}#`);
    if (rootName) {
      const { $defs: _, ...root } = schema;
      decls.push(declare(rootName, root, file, file));
    } else if (schema.type !== undefined || schema.properties !== undefined) {
      fail(file, "schema root has a type but is not referenced by the catalog");
    }
    for (const [def, s] of Object.entries(schema.$defs ?? {})) {
      decls.push(declare(names.get(`${file}#${def}`)!, s as Schema, file, `${file}#/$defs/${def}`));
    }
  }
  return `${HEADER}\n${decls.join("\n")}`;
}

function messagesTs(): string {
  const types = Object.keys(catalog.messages);
  const imports = [...new Set(["RawEnvelope", ...types.map((t) => `${pascal(t)}Payload`)])].sort();
  const entries = types.map((t) => `  ${JSON.stringify(t)}: ${pascal(t)}Payload;`).join("\n");
  const list = types.map((t) => `  ${JSON.stringify(t)},`).join("\n");
  return `${HEADER}
import type {
${imports.map((n) => `  ${n},`).join("\n")}
} from "./protocol.js";

/** Envelope \`v\` this SDK speaks (protocol/catalog.json). */
export const PROTOCOL_VERSION = ${JSON.stringify(catalog.v)} as const;

/** Payload type for each envelope \`type\` in protocol/catalog.json. */
export interface MessagePayloads {
${entries}
}

export type MessageType = keyof MessagePayloads;

/** Every message type in protocol/catalog.json, in catalog order. */
export const MESSAGE_TYPES = [
${list}
] as const satisfies readonly MessageType[];

/** An envelope whose payload is typed by its \`type\`. */
export type Envelope<T extends MessageType = MessageType> = Omit<RawEnvelope, "type" | "payload"> & {
  type: T;
  payload: MessagePayloads[T];
};

/** Discriminated union of every typed envelope; narrow on \`type\`. */
export type AnyEnvelope = { [T in MessageType]: Envelope<T> }[MessageType];
`;
}

const outputs: Record<string, string> = {
  "protocol.ts": protocolTs(),
  "messages.ts": messagesTs(),
  "index.ts": `${HEADER}\nexport * from "./protocol.js";\nexport * from "./messages.js";\n`,
};

if (process.argv.includes("--check")) {
  const stale: string[] = [];
  for (const [name, content] of Object.entries(outputs)) {
    const path = join(OUT, name);
    if (!existsSync(path)) stale.push(`missing ${name}`);
    else if (readFileSync(path, "utf8") !== content) stale.push(`out of date ${name}`);
  }
  if (existsSync(OUT)) {
    for (const f of readdirSync(OUT)) if (!(f in outputs)) stale.push(`unexpected ${f}`);
  }
  if (stale.length) {
    console.error(`src/generated is stale relative to protocol/:\n  ${stale.join("\n  ")}\nRun \`npm run gen\` in sdk/typescript and commit the result.`);
    process.exit(1);
  }
  console.log(`src/generated is up to date (${Object.keys(outputs).length} files).`);
} else {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(outputs)) writeFileSync(join(OUT, name), content);
  console.log(`wrote ${Object.keys(outputs).length} files to src/generated`);
}
