# Code generated by sdk/python/scripts/gen.py from protocol/. DO NOT EDIT.
# Regenerate with `python scripts/gen.py` (in sdk/python).
"""Protocol types for fleet-server, generated from protocol/schemas.

Every message is plain JSON; these TypedDicts describe the dicts `json.loads`
returns and `json.dumps` accepts. They cost nothing at runtime.
"""

import sys
from typing import Any, Final, Literal, Union

if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict
else:  # NotRequired arrived in 3.11; typing_extensions backports it with a TypedDict that honours it.
    from typing_extensions import NotRequired, TypedDict


class AgentInfo(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/agentInfo`"""

    name: NotRequired[str]
    version: NotRequired[str]


class EnrollRequestPayload(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/enroll.request`"""

    #: Fleet enrollment key for kind robot/service; the single-use operator invite key for kind operator. One field, one enroll flow.
    enrollment_key: str
    kind: Literal["robot", "service", "operator"]
    name: NotRequired[str]
    agent: NotRequired[AgentInfo]


class EnrollResponsePayload(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/enroll.response`"""

    token: str
    client_id: str
    fleet_id: str


class HelloPayload(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/hello`"""

    token: str
    agent: NotRequired[AgentInfo]


# Source: `protocol/schemas/defs.schema.json#/$defs/clientKind`
ClientKind = Literal["robot", "service", "operator"]


class WelcomePayload(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/welcome`"""

    client_id: str
    fleet_id: str
    kind: ClientKind
    server_time_ms: int
    heartbeat_interval_ms: int


class HeartbeatPayload(TypedDict):
    """Source: `protocol/schemas/auth.schema.json#/$defs/heartbeat`"""


# Source: `protocol/schemas/defs.schema.json#/$defs/channelName`
ChannelName = str


class ChannelPublishTo(TypedDict):
    """Branch of ChannelPublishPayload: sets `to`.

    Source: `protocol/schemas/bus.schema.json#/$defs/channel.publish/oneOf/0`
    """

    channel: ChannelName
    to: str
    data: Any


class ChannelPublishBroadcast(TypedDict):
    """Branch of ChannelPublishPayload: sets `broadcast`.

    Source: `protocol/schemas/bus.schema.json#/$defs/channel.publish/oneOf/1`
    """

    channel: ChannelName
    broadcast: Literal[True]
    data: Any


# Source: `protocol/schemas/bus.schema.json#/$defs/channel.publish`
ChannelPublishPayload = Union[ChannelPublishTo, ChannelPublishBroadcast]


# Source: `protocol/schemas/bus.schema.json#/$defs/channel.message`
ChannelMessagePayload = TypedDict(
    "ChannelMessagePayload",
    {
        "channel": ChannelName,
        "from": str,
        "data": Any,
    },
)


# WebRTC signaling relay. Sender sets `to`; the server stamps `from` on delivery.
#
# Source: `protocol/schemas/bus.schema.json#/$defs/signal`
SignalPayload = TypedDict(
    "SignalPayload",
    {
        "to": NotRequired[str],
        "from": NotRequired[str],
        "kind": Literal["offer", "answer", "ice"],
        "data": Any,
    },
)


class IceRequestPayload(TypedDict):
    """Asks the server for the ICE servers to give a peer connection. Robots and operators only. The reply is ice.config.

    Source: `protocol/schemas/bus.schema.json#/$defs/ice.request`
    """


class IceServer(TypedDict):
    """One STUN or TURN server in the shape of WebRTC's RTCIceServer, so it can be passed to a peer connection unchanged. The three field names are WebRTC's, not this protocol's.

    Source: `protocol/schemas/defs.schema.json#/$defs/iceServer`
    """

    #: stun:, stuns:, turn: or turns: URLs of one server. Always an array.
    urls: list[str]
    username: NotRequired[str]
    credential: NotRequired[str]


class IceConfigPayload(TypedDict):
    """The reply to ice.request: the ICE servers this installation is configured with, with TURN credentials minted for the asking client.

    Source: `protocol/schemas/bus.schema.json#/$defs/ice.config`
    """

    #: Pass as RTCConfiguration.iceServers. Empty when the installation has none configured.
    ice_servers: list[IceServer]
    #: Epoch milliseconds, server clock, after which the credentials in ice_servers are refused for a new allocation. Absent when no entry carries credentials.
    expires_at_ms: NotRequired[int]
    #: The envelope id of the ice.request this answers; absent when the request had none.
    ref: NotRequired[str]


class LayerDeclarePayload(TypedDict):
    """Source: `protocol/schemas/bus.schema.json#/$defs/layer.declare`"""

    layer_id: ChannelName
    kind: Literal["geojson"]
    title: NotRequired[str]
    style: NotRequired[dict[str, Any]]


class LayerUpdatePayload(TypedDict):
    """Source: `protocol/schemas/bus.schema.json#/$defs/layer.update`"""

    layer_id: ChannelName
    data: Any


# Source: `protocol/schemas/defs.schema.json#/$defs/robotState`
RobotState = Literal["AUTONOMOUS", "HELP_REQUESTED", "TELEOP"]


# Source: `protocol/schemas/defs.schema.json#/$defs/presence`
Presence = Literal["online", "offline"]


class GeoPose(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/geoPose`"""

    frame: Literal["geographic"]
    lat: float
    lon: float
    alt_m: NotRequired[float]
    yaw_rad: NotRequired[float]


class LocalPose(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/localPose`"""

    frame: Literal["local"]
    frame_id: NotRequired[str]
    x_m: float
    y_m: float
    z_m: NotRequired[float]
    yaw_rad: NotRequired[float]


# Source: `protocol/schemas/defs.schema.json#/$defs/pose`
Pose = Union[GeoPose, LocalPose]


class ManifestDrive(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/manifest/properties/drive`"""

    type: Literal["twist"]
    max_v_mps: float
    max_w_radps: float


class ManifestCamerasItem(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/manifest/properties/cameras/items`"""

    id: str
    label: NotRequired[str]


class ManifestBattery(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/manifest/properties/battery`"""


class Manifest(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/manifest`"""

    drive: NotRequired[ManifestDrive]
    cameras: NotRequired[list[ManifestCamerasItem]]
    battery: NotRequired[ManifestBattery]
    channels: NotRequired[list[ChannelName]]
    behaviors: NotRequired[list[str]]


class Lease(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/lease`"""

    lease_id: str
    robot_id: str
    operator_id: str
    expires_at_ms: int


class HelpDetails(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/helpDetails`"""

    reason: str
    context: NotRequired[dict[str, Any]]
    requested_at_ms: int


class RobotSummary(TypedDict):
    """Source: `protocol/schemas/defs.schema.json#/$defs/robotSummary`"""

    robot_id: str
    name: NotRequired[str]
    presence: Presence
    state: RobotState
    manifest: NotRequired[Manifest]
    lease: NotRequired[Lease]
    help: NotRequired[HelpDetails]


class OperatorSummary(TypedDict):
    """One operator of the fleet, as listed in snapshot.operators and carried as the data of operator.* events. Fields are only ever added.

    Source: `protocol/schemas/defs.schema.json#/$defs/operatorSummary`
    """

    operator_id: str
    name: NotRequired[str]
    online: bool
    #: The robot this operator is looking at. Absent when it is watching none; never set while online is false.
    watching: NotRequired[str]


# Source: `protocol/schemas/defs.schema.json#/$defs/eventName`
EventName = Literal["robot.online", "robot.offline", "robot.telemetry", "robot.help_requested", "robot.lease_granted", "robot.lease_released", "robot.lease_revoked", "operator.online", "operator.offline", "operator.watching"]


class RawEnvelope(TypedDict):
    """Source: `protocol/schemas/envelope.schema.json`"""

    v: Literal[0]
    type: str
    id: NotRequired[str]
    ts_ms: NotRequired[int]
    payload: dict[str, Any]


class ErrorPayload(TypedDict):
    """Source: `protocol/schemas/error.schema.json#/$defs/error`"""

    code: Literal["auth_failed", "invalid_message", "not_found", "not_authorized", "conflict", "rate_limited"]
    message: str
    ref: NotRequired[str]
    #: Set only on the conflict that refuses a lease.claim: the lease that is in the way, as held at the moment of the refusal.
    lease: NotRequired[Lease]


class SubscribePayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/subscribe`"""

    topics: list[str]


class SnapshotPayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/snapshot`"""

    robots: list[RobotSummary]
    #: Every operator of the fleet that is not revoked, online or not. The server always sends it.
    operators: NotRequired[list[OperatorSummary]]


class EventPayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/event`"""

    event: EventName
    #: The robot the event is about. Set on every robot.* event, absent otherwise.
    robot_id: NotRequired[str]
    #: The operator the event is about. Set on every operator.* event, absent otherwise.
    operator_id: NotRequired[str]
    data: NotRequired[dict[str, Any]]


class LeaseClaimPayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/lease.claim`"""

    robot_id: str
    #: True to take the robot from another operator who holds its lease (revoke + reissue). Absent or false, a claim on a robot leased to another operator is refused with error{code: conflict}.
    steal: NotRequired[bool]


# Source: `protocol/schemas/ops.schema.json#/$defs/lease.granted`
LeaseGrantedPayload = Lease


class LeaseRenewPayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/lease.renew`"""

    lease_id: str


class LeaseReleasePayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/lease.release`"""

    lease_id: str
    resolution: Literal["resolved", "abandoned"]


class LeaseRevokedPayload(TypedDict):
    """Source: `protocol/schemas/ops.schema.json#/$defs/lease.revoked`"""

    lease_id: str
    robot_id: str
    reason: Literal["released", "expired", "stolen", "operator_lost"]
    help: NotRequired[HelpDetails]


class WatchPayload(TypedDict):
    """Operator to server: which robot this operator is looking at. It lasts as long as the connection that sent it.

    Source: `protocol/schemas/ops.schema.json#/$defs/watch`
    """

    #: A robot of the operator's fleet, or null to stop watching.
    robot_id: Union[str, None]


# Source: `protocol/schemas/robot.schema.json#/$defs/manifest`
ManifestPayload = Manifest


class TelemetryVelocity(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/telemetry/properties/velocity`"""

    v_mps: NotRequired[float]
    w_radps: NotRequired[float]


class TelemetryBattery(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/telemetry/properties/battery`"""

    pct: NotRequired[float]
    voltage: NotRequired[float]


class TelemetryPayload(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/telemetry`"""

    pose: NotRequired[Pose]
    velocity: NotRequired[TelemetryVelocity]
    battery: NotRequired[TelemetryBattery]
    health: NotRequired[dict[str, Union[str, float, bool]]]


class HelpRequestPayload(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/help.request`"""

    reason: str
    context: NotRequired[dict[str, Any]]


class TwistLinear(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/twist/properties/linear`"""

    x_mps: float
    y_mps: NotRequired[float]


class TwistAngular(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/twist/properties/angular`"""

    z_radps: float


class TwistPayload(TypedDict):
    """Source: `protocol/schemas/robot.schema.json#/$defs/twist`"""

    lease_id: str
    linear: TwistLinear
    angular: TwistAngular


#: Envelope `v` this SDK speaks (protocol/catalog.json).
PROTOCOL_VERSION: Final = 0

MessageType = Literal[
    "enroll.request",
    "enroll.response",
    "hello",
    "welcome",
    "heartbeat",
    "manifest",
    "telemetry",
    "help.request",
    "twist",
    "subscribe",
    "snapshot",
    "event",
    "lease.claim",
    "lease.granted",
    "lease.renew",
    "lease.release",
    "lease.revoked",
    "watch",
    "channel.publish",
    "channel.message",
    "signal",
    "ice.request",
    "ice.config",
    "layer.declare",
    "layer.update",
    "error",
]

#: Every message type in protocol/catalog.json, in catalog order.
MESSAGE_TYPES: Final[tuple[MessageType, ...]] = (
    "enroll.request",
    "enroll.response",
    "hello",
    "welcome",
    "heartbeat",
    "manifest",
    "telemetry",
    "help.request",
    "twist",
    "subscribe",
    "snapshot",
    "event",
    "lease.claim",
    "lease.granted",
    "lease.renew",
    "lease.release",
    "lease.revoked",
    "watch",
    "channel.publish",
    "channel.message",
    "signal",
    "ice.request",
    "ice.config",
    "layer.declare",
    "layer.update",
    "error",
)

#: Payload TypedDict for each envelope `type` in protocol/catalog.json.
PAYLOAD_TYPES: Final[dict[str, Any]] = {
    "enroll.request": EnrollRequestPayload,
    "enroll.response": EnrollResponsePayload,
    "hello": HelloPayload,
    "welcome": WelcomePayload,
    "heartbeat": HeartbeatPayload,
    "manifest": ManifestPayload,
    "telemetry": TelemetryPayload,
    "help.request": HelpRequestPayload,
    "twist": TwistPayload,
    "subscribe": SubscribePayload,
    "snapshot": SnapshotPayload,
    "event": EventPayload,
    "lease.claim": LeaseClaimPayload,
    "lease.granted": LeaseGrantedPayload,
    "lease.renew": LeaseRenewPayload,
    "lease.release": LeaseReleasePayload,
    "lease.revoked": LeaseRevokedPayload,
    "watch": WatchPayload,
    "channel.publish": ChannelPublishPayload,
    "channel.message": ChannelMessagePayload,
    "signal": SignalPayload,
    "ice.request": IceRequestPayload,
    "ice.config": IceConfigPayload,
    "layer.declare": LayerDeclarePayload,
    "layer.update": LayerUpdatePayload,
    "error": ErrorPayload,
}
